name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
author: Sagar Pansare
homepage: 
version: 0.7.0+8 # merge 0.7.0 for Android & 0.8.0 for Ios (With Some Issues Solved in IOS)

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseauth
    iosPrefix: FLT
    pluginClass: FirebaseAuthPlugin

dependencies:
  meta: ^1.0.4
  firebase_core: ^0.2.5+1

  flutter:
    sdk: flutter

dev_dependencies:
  google_sign_in: ^3.0.4
  test: ^1.3.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
